import type { GraphAnalysisInput } from "../shared/types.js";

type StoryAnalysisPrompt = {
  system: string;
  user: string;
};

export function buildStoryAnalysisPrompt(input: GraphAnalysisInput): StoryAnalysisPrompt {
  return {
    system: [
      "당신은 장편 소설의 설정 붕괴를 검수하는 StoryGuard 분석기입니다.",
      "settingsText, manuscriptText, RAG evidence, relatedSettings만 근거로 사용하세요.",
      "근거에 없는 사실을 추측으로 지어내지 마세요.",
      "다만 근거 안에서 고유명사·용어·명칭·수치·신분·능력·관계가 서로 다르게 나오면, 차이가 작더라도 그것은 '명확한 불일치'이므로 반드시 보고하세요.",
      "서로 다른 항목의 불일치는 하나로 묶지 말고 각각 별도 issue로 분리하세요.",
      "반드시 JSON schema에 맞는 GraphAnalysisResult JSON만 반환하세요.",
      "JSON 외 설명 문장과 Markdown 코드블록은 출력하지 마세요.",
      "title, reason, suggestion 등 모든 텍스트는 한국어로 작성하세요.",
    ].join("\n"),
    user: [
      "아래 입력을 분석해서 GraphAnalysisResult JSON을 반환하세요.",
      "",
      "[프로젝트]",
      `title: ${input.request.projectTitle}`,
      `genre: ${input.request.genre ?? ""}`,
      "",
      "[설정집 settingsText]",
      input.request.settingsText,
      "",
      "[검사할 원고 manuscriptText]",
      input.request.manuscriptText,
      "",
      "[RAG evidence]",
      JSON.stringify(input.evidence, null, 2),
      "",
      "[RAG relatedSettings]",
      JSON.stringify(input.relatedSettings, null, 2),
      "",
      "[세부 일관성 검사 — 빠짐없이]",
      "원고(manuscriptText)를 설정/이전 버전(evidence, relatedSettings)과 항목별로 대조하세요.",
      "작은 표기·명칭 차이라도 불일치하면 '각각 별도 issue'로 보고하세요. 큰 충돌 하나로 묶지 마세요.",
      "- 고유명사: 인물·장소·아이템 이름 (예: 유리왕관 vs 나무왕관)",
      "- 용어/개념 명칭 (예: '피의 계승권' vs '물의 계승권')",
      "- 수치: 시간·나이·거리·횟수·날짜",
      "- 능력/제약/금지조건",
      "- 신분·관계 (예: 왕족 vs 평민)",
      "이런 세부 표기/용어 불일치는 가장 가까운 type(주로 character_conflict 또는 world_rule_conflict)으로 분류하고, severity는 보통 low~medium 으로 두세요.",
      "한 문장 안에 여러 불일치가 있어도 항목마다 issue를 1개씩 만들고, 절대 하나로 합치지 마세요.",
      "",
      "[세부 불일치 분리 예시]",
      "설정: \"유리왕관은 피의 계승권을 가진 왕족만 착용한다.\"",
      "원고: \"서지안은 물의 계승권을 가진 평민이며 나무왕관을 착용했다.\"",
      "→ 최소 3개 issue로 분리해야 함:",
      "  1) 용어 불일치: '피의 계승권'(설정) vs '물의 계승권'(원고) — severity low",
      "  2) 신분 불일치: '왕족'(설정) vs '평민'(원고) — severity medium",
      "  3) 명칭 불일치: '유리왕관'(설정) vs '나무왕관'(원고) — severity low",
      "",
      "[허용되는 issue.type]",
      "- character_conflict: 인물 성격, 능력, 관계, 상태가 설정과 충돌",
      "- world_rule_conflict: 세계관 규칙, 마법/과학 규칙, 금지 조건 위반",
      "- timeline_conflict: 사건 순서, 날짜, 등장 시점 충돌",
      "- causality_conflict: 원인 없이 결과가 생기거나 기존 사건 흐름과 모순",
      "- foreshadowing_gap: 설정된 복선/단서/아이템이 필요한 장면에서 빠짐",
      "",
      "[severity 기준]",
      "- high: 핵심 세계관 규칙, 생사, 주인공 능력, 결말에 직접 영향",
      "- medium: 사건 순서, 인물 위치, 관계, 원인/결과에 영향",
      "- low: 복선 회수, 설명 부족, 장면 설득력 약화",
      "",
      "[반드시 이 JSON 형태로만 출력]",
      '{"issues":[{"id":"i1","type":"world_rule_conflict","severity":"low","title":"...","manuscriptQuote":"...","conflictingSetting":"...","reason":"...","suggestion":"...","relatedNodeIds":["n1"],"evidenceIds":["ev1"]}],"nodes":[{"id":"n1","label":"...","type":"rule","importance":3,"hasIssue":true}],"edges":[{"source":"n1","target":"n1","label":"...","type":"violates"}]}',
      "이슈가 없으면 issues는 빈 배열 []. nodes/edges도 비면 [].",
      "",
      "[출력 요구]",
      "- issues, nodes, edges만 반환하세요.",
      "- issue.evidenceIds는 입력 evidence에 존재하는 id만 사용하세요.",
      "- issue.relatedNodeIds는 출력 nodes에 존재하는 id만 사용하세요.",
      "- edge.source와 edge.target은 출력 nodes에 존재하는 id만 사용하세요.",
      "- suggestion은 작가가 바로 적용할 수 있는 수정 제안으로 작성하세요.",
    ].join("\n"),
  };
}
